POST http://localhost:3003/api/login/
Content-Type: application/json

{
  "username": "maslenaф",
  "password": "password"
}
###
POST http://localhost:3003/api/login/
Content-Type: application/json

{
  "username": "maslenaф",
  "password": "wrongpassword"
}
