
###
GET http://localhost:3001/api/persons/4
###
GET http://localhost:3001/api/persons/
###
DELETE http://localhost:5173/api/persons/689ecc1ca9a27930ce6bc5192
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "jusii",
  "number": "545454545454"
}
###
DeLETE https://fso-nodejs-server-homework.onrender.com/api/persons/4
